### Get all books
GET http://localhost:3000/api/book

### Get a book by ID
GET http://localhost:3000/api/book/1

### Create a new book
POST http://localhost:3000/api/book
Content-Type: application/json

{
  "title": "New Book",
  "author": "Author Name",
  "publishedDate": "2023-01-01"
}

### Update a book by ID
PUT http://localhost:3000/api/book/1
Content-Type: application/json

{
  "title": "Updated Book Title",
  "author": "Updated Author Name",
  "publishedDate": "2023-01-02"
}

### Delete a book by ID
DELETE http://localhost:3000/api/book/1
