name: CI/CD

on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本號碼'
        required: true

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  VERSION: ${{ github.event.inputs.version }}
  COMMIT_SHA: ${{ github.sha }}
  IMAGE_TAG: ${{ secrets.ECR_REPOSITORY }}:${{ github.event.inputs.version }}-${{ github.sha }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: TypeScript compile check
      run: npm run build

    - name: Run tests
      run: npm test

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker image
      run: |
        echo "Building image: $IMAGE_TAG"
        docker build -t $IMAGE_TAG .
        echo "Built image: $IMAGE_TAG"

    - name: Push Docker image to ECR
      run: |
        docker push $IMAGE_TAG
        echo "Pushed image: $IMAGE_TAG"