name: CI/CD

on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本號碼'
        required: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 檢出程式碼
      - name: Checkout code
        uses: actions/checkout@v3

      # 設定 Node.js 環境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 輸出版本號碼
      - name: Set version
        run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      # 安裝依賴
      - name: Install dependencies
        run: npm install

      # 執行 TypeScript 編譯檢查
      - name: TypeScript compile check
        run: npm run build

      # 執行測試
      - name: Run tests
        run: npm test
